Omnichannel
- '@KevLehman'
- '@aleksandernsilva'
- '@cauefcr'
- '@tiagoevanp'
- '@MartinSchoeler'
- '@murtaza98'

ChatEngine
- '@jeanfbrito'
- '@tassoevan'
- '@ggazzo'
- '@sampaiodiego'
- '@pierre-lehnen-rc'
- '@juliajforesti'
- '@felipe-rod123'

AppsEngine
- '@thassiov'
- '@graywolf336'
- '@d-gubert'
- '@albuquerquefabio'
- '@tapiarafael'
- '@AllanPazRibeiro'

Cloud
- '@geekgonecrazy'

TeamCollaboration
- '@filipemarins'
- '@matheusbsilva137'
- '@gabriellsh'
- '@guijun13'
- '@LucianoPierdona'
