tasks:
  - init: curl https://install.meteor.com/ | sh \
      && PATH=$PATH:$HOME/.meteor \
      && meteor npm install
    command: meteor npm start
ports:
  - port: 3000
    onOpen: open-preview
image:
  file: .gitpod.Dockerfile
