# .kodiak.toml
version = 1


[merge.message]
title = "pull_request_title" # default: "github_default"
body = "pull_request_body" # default: "github_default"
[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[merge]
method = "squash"
	[message]
    include_coauthors=true
automerge_label = ["stat: ready to merge", "QA tested", "automerge"]
