sudo: false
language: node_js
node_js:
  - "0.10"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
before_script: 'npm install -g istanbul
script:
  - meteor build --server chat-locker ./
