sudo: false
language: node_js
node_js:
  - "0.10"

branches:
  except:
    - gh-pages

before_script: 'npm install -g istanbul && coveralls --save'
before_install:
  - "curl https://install.meteor.com | /bin/sh"
script:
  - meteor build --server chat-locker ./
