name: Bug report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
        If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support
        If you are experiencing a bug please search our issues to be sure it is not already present: https://github.com/RocketChat/Rocket.Chat/issues
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the problem.
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '....'
        3. and so on...
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: What you expect to happen
  - type: textarea
    validations:
      required: true
    attributes:
      label: Actual behavior
      description: What actually happens with SCREENSHOT, if applicable
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: textarea
    attributes:
      label: Relevant logs
      description: |
        Logs from both SERVER and BROWSER
        For more information about collecting logs please see: https://rocket.chat/docs/contributing/reporting-issues#gathering-logs
