name: 'Auto label QA'
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ggazzo/gh-action-auto-label@beta-2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
