name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.15.x, 8.14.x]

    steps:
    - uses: actions/checkout@v1
      
    - uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm ci
    - name: npm lint and test
      run: |
        npm run jslint
        npm run testunit
      env:
        CI: true
