name: Start Rocket.Chat micro service Docker container

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      imageTag:
        required: true
        type: string

jobs:
  run-micro-service:
    name: Start up Rocket.Chat
    runs-on: ubuntu-latest
    steps:
      - run: |
          LOWERCASE_REPOSITORY=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")

          # spin up all micro services
          docker run --name ${{ inputs.service }} -d \
            --link mongo \
            --link nats \
            -e MONGO_URL=mongodb://mongo:27017/rocketchat \
            -e MONGO_OPLOG_URL=mongodb://mongo:27017/local \
            -e TRANSPORTER=nats://nats:4222 \
            -e MOLECULER_LOG_LEVEL=info \
            ghcr.io/${LOWERCASE_REPOSITORY}/${{ inputs.service }}-service:${{ inputs.imageTag }}

          until echo "$(docker logs ${{ inputs.service }})" | grep -q "NetworkBroker started successfully"; do
            echo "Waiting '${{ inputs.service }}' to start up"
            ((c++)) && ((c==10)) && exit 1
            sleep 10
          done
